---
engines:
  ruff:
    enabled: true
  trivy:
    enabled: false
  bandit:
    enabled: false
  pylint:
    enabled: false
  pylintpython3:
    enabled: false
  eslint:
    enabled: false
  eslint-8:
    enabled: false
  eslint-9:
    enabled: false
  prospector:
    enabled: false
  stylelint:
    enabled: false
  markdownlint:
    enabled: false
  checkov:
    enabled: false
  semgrep:
    enabled: false
  lizard:
    enabled: false
  pmd:
    enabled: false
  pmd-7:
    enabled: false
  spotbugs:
    enabled: false
  codenarc:
    enabled: false
  rubocop:
    enabled: false
  brakeman:
    enabled: false
  flawfinder:
    enabled: false
  hadolint:
    enabled: false
  shellcheck:
    enabled: false
  remark-lint:
    enabled: false
  csslint:
    enabled: false
  jacksonlinter:
    enabled: false
exclude_paths:
  - .venv/
  - node_modules/
  - htmlcov/
  - static/
  - staticfiles/
  - media/
  - logs/
  - _archive/
  - .ruff_cache/
  - .coverage
  - "**/*.pdf"
  - "*.pdf"
  - "**/*.sqlite3"
  - "*.sqlite3"
  - "**/*.pyc"
  - "*.pyc"
  - results.sarif

