ignore-patterns:
  - .venv
  - migrations
  - tests
  - _archive

tools:
  dodgy:
    run: false
  pylint:
    options:
      load-plugins: pylint_django
      disable:
        - cyclic-import
        - protected-access
        - unused-argument
        - django-not-configured
  mccabe:
    run: false
