# Generated by Django 5.2.8 on 2025-11-20 18:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Official company name", max_length=255),
                ),
                (
                    "registered_id",
                    models.CharField(
                        blank=True,
                        help_text="Company registration number",
                        max_length=100,
                    ),
                ),
                (
                    "registered_address",
                    models.TextField(help_text="Registered business address"),
                ),
                (
                    "customer_id",
                    models.CharField(
                        help_text="Internal customer reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "total_employee_count",
                    models.PositiveIntegerField(
                        help_text="Total number of employees across all sites",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("contact_telephone", models.CharField(blank=True, max_length=50)),
                ("contact_fax", models.CharField(blank=True, max_length=50)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_website", models.URLField(blank=True)),
                ("signatory_name", models.CharField(blank=True, max_length=255)),
                ("signatory_title", models.CharField(blank=True, max_length=255)),
                (
                    "ms_representative_name",
                    models.CharField(
                        blank=True,
                        help_text="Management System Representative name",
                        max_length=255,
                    ),
                ),
                (
                    "ms_representative_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Standard code (e.g., 'ISO 9001:2015')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Full title of the standard", max_length=255
                    ),
                ),
                (
                    "nace_code",
                    models.CharField(
                        blank=True, help_text="NACE classification code", max_length=50
                    ),
                ),
                (
                    "ea_code",
                    models.CharField(
                        blank=True,
                        help_text="EA (European Accreditation) code",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Standard",
                "verbose_name_plural": "Standards",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        help_text="Name of the site/location", max_length=255
                    ),
                ),
                (
                    "site_address",
                    models.TextField(help_text="Physical address of the site"),
                ),
                (
                    "site_employee_count",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of employees at this site (optional)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "site_scope_override",
                    models.TextField(
                        blank=True,
                        help_text="Optional scope description specific to this site",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="Whether this site is currently active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site",
                "verbose_name_plural": "Sites",
                "ordering": ["organization", "site_name"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certification_scope",
                    models.TextField(help_text="Scope of the certification"),
                ),
                (
                    "certificate_id",
                    models.CharField(
                        blank=True,
                        help_text="Certificate number/reference",
                        max_length=100,
                    ),
                ),
                (
                    "certificate_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("withdrawn", "Withdrawn"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("issue_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="core.organization",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certifications",
                        to="core.standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification",
                "verbose_name_plural": "Certifications",
                "ordering": ["organization", "standard"],
                "unique_together": {("organization", "standard")},
            },
        ),
    ]
