# Generated by Django 5.2.8 on 2025-11-24 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("audit_management", "0001_initial"),
        ("certification", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveillanceSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("cycle_start", models.DateField(help_text="Certification cycle start (Stage 2 decision date)")),
                ("cycle_end", models.DateField(help_text="Certification cycle end (3 years from start)")),
                ("surveillance_1_due_date", models.DateField()),
                ("surveillance_2_due_date", models.DateField()),
                ("recertification_due_date", models.DateField()),
                ("surveillance_1_completed", models.BooleanField(default=False)),
                ("surveillance_2_completed", models.BooleanField(default=False)),
                ("recertification_completed", models.BooleanField(default=False)),
                ("overdue_alert_sent", models.BooleanField(default=False)),
                ("expiry_warning_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surveillance_schedule",
                        to="core.certification",
                    ),
                ),
                (
                    "recertification_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recertification_for",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "surveillance_1_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveillance_1_for",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "surveillance_2_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="surveillance_2_for",
                        to="audit_management.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Surveillance Schedule",
                "verbose_name_plural": "Surveillance Schedules",
                "ordering": ["-cycle_start"],
            },
        ),
        migrations.CreateModel(
            name="CertificateHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("issued", "Certificate Issued"),
                            ("renewed", "Certificate Renewed"),
                            ("surveillance_passed", "Surveillance Audit Passed"),
                            ("suspended", "Certificate Suspended"),
                            ("suspension_lifted", "Suspension Lifted"),
                            ("withdrawn", "Certificate Withdrawn"),
                            ("expired", "Certificate Expired"),
                            ("scope_extended", "Scope Extended"),
                            ("scope_reduced", "Scope Reduced"),
                            ("transfer_in", "Transferred In"),
                            ("transfer_out", "Transferred Out"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_date", models.DateField()),
                ("certificate_number_snapshot", models.CharField(blank=True, max_length=100)),
                ("certification_scope_snapshot", models.TextField(blank=True)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("action_reason", models.TextField(blank=True)),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_history_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="history", to="core.certification"
                    ),
                ),
                (
                    "related_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_history_entries",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "related_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certificate_history_entries",
                        to="certification.certificationdecision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificate History",
                "verbose_name_plural": "Certificate History Entries",
                "ordering": ["-action_date", "-created_at"],
                "indexes": [
                    models.Index(fields=["action"], name="core_certif_action_64aaaf_idx"),
                    models.Index(fields=["action_date"], name="core_certif_action__814278_idx"),
                ],
            },
        ),
    ]
