# Generated by Django 5.2.8 on 2025-11-24 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("identity", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditorCompetenceEvaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("evaluation_date", models.DateField()),
                ("technical_knowledge_score", models.PositiveIntegerField()),
                ("audit_skills_score", models.PositiveIntegerField()),
                ("communication_skills_score", models.PositiveIntegerField()),
                ("report_writing_score", models.PositiveIntegerField()),
                ("witness_audit_date", models.DateField(blank=True, null=True)),
                ("witness_audit_notes", models.TextField(blank=True)),
                (
                    "overall_assessment",
                    models.CharField(
                        choices=[
                            ("exceeds", "Exceeds Requirements"),
                            ("meets", "Meets Requirements"),
                            ("development_needed", "Development Needed"),
                            ("unsatisfactory", "Unsatisfactory"),
                        ],
                        max_length=30,
                    ),
                ),
                ("development_plan", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competence_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "witness_audit_observer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="witness_audits_observed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditor Competence Evaluation",
                "verbose_name_plural": "Auditor Competence Evaluations",
                "ordering": ["-evaluation_date"],
                "db_table": "accounts_auditorcompetenceevaluation",
            },
        ),
        migrations.CreateModel(
            name="AuditorTrainingRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("course_title", models.CharField(max_length=255)),
                ("training_provider", models.CharField(max_length=255)),
                ("course_date", models.DateField()),
                ("duration_hours", models.FloatField(blank=True, null=True)),
                ("cpd_points", models.FloatField(default=0.0, help_text="Continuing Professional Development points")),
                ("certificate_file", models.FileField(blank=True, upload_to="training_certificates/")),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standards_covered",
                    models.ManyToManyField(blank=True, related_name="training_records", to="core.standard"),
                ),
            ],
            options={
                "verbose_name": "Auditor Training Record",
                "verbose_name_plural": "Auditor Training Records",
                "ordering": ["-course_date"],
                "db_table": "accounts_auditortrainingrecord",
            },
        ),
        migrations.CreateModel(
            name="AuditorQualification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "qualification_type",
                    models.CharField(
                        choices=[
                            ("lead_auditor_cert", "Lead Auditor Certificate"),
                            ("auditor_cert", "Auditor Certificate"),
                            ("technical_expert_cert", "Technical Expert Certificate"),
                            ("sector_qualification", "Sector-Specific Qualification"),
                            ("language_cert", "Language Certification"),
                        ],
                        max_length=40,
                    ),
                ),
                ("issuing_body", models.CharField(max_length=255)),
                ("certificate_number", models.CharField(max_length=100)),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "nace_codes",
                    models.CharField(
                        blank=True, help_text="Comma-separated NACE codes for sector competence", max_length=255
                    ),
                ),
                (
                    "ea_codes",
                    models.CharField(
                        blank=True, help_text="Comma-separated EA codes for sector competence", max_length=255
                    ),
                ),
                ("certificate_file", models.FileField(blank=True, upload_to="auditor_qualifications/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("expired", "Expired"),
                            ("suspended", "Suspended"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standards",
                    models.ManyToManyField(blank=True, related_name="auditor_qualifications", to="core.standard"),
                ),
            ],
            options={
                "verbose_name": "Auditor Qualification",
                "verbose_name_plural": "Auditor Qualifications",
                "ordering": ["auditor", "-issue_date"],
                "indexes": [models.Index(fields=["status"], name="accounts_au_status_b1121b_idx")],
                "db_table": "accounts_auditorqualification",
            },
        ),
        migrations.CreateModel(
            name="ConflictOfInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("former_employee", "Former Employee"),
                            ("consultant", "Consultant / Advisory"),
                            ("family_member", "Family Member Employed"),
                            ("financial_interest", "Financial Interest"),
                            ("competing_business", "Competing Business"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField()),
                ("declared_date", models.DateField(auto_now_add=True)),
                ("relationship_start_date", models.DateField(blank=True, null=True)),
                ("relationship_end_date", models.DateField(blank=True, null=True)),
                (
                    "impartiality_risk",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High - Assignment Prohibited")],
                        default="low",
                        max_length=20,
                    ),
                ),
                ("mitigation_measures", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coi_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_of_interest",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts_declared",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conflict of Interest",
                "verbose_name_plural": "Conflicts of Interest",
                "ordering": ["-declared_date"],
                "indexes": [models.Index(fields=["impartiality_risk"], name="accounts_co_imparti_cdd420_idx")],
                "db_table": "accounts_conflictofinterest",
            },
        ),
        migrations.CreateModel(
            name="ImpartialityDeclaration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("declaration_period_year", models.PositiveIntegerField()),
                ("declaration_date", models.DateField(auto_now_add=True)),
                ("no_conflicts_declared", models.BooleanField(default=False)),
                ("conflicts_detailed", models.TextField(blank=True)),
                ("declaration_accepted", models.BooleanField(default=False)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="impartiality_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impartiality_declarations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Impartiality Declaration",
                "verbose_name_plural": "Impartiality Declarations",
                "ordering": ["-declaration_date"],
                "unique_together": {("user", "declaration_period_year")},
                "db_table": "accounts_impartialitydeclaration",
            },
        ),
    ]
