# Generated by Django 6.0 on 2025-12-03 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit_management", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("grant", "Grant Certification"),
                            ("refuse", "Refuse Certification"),
                            ("suspend", "Suspend Certification"),
                            ("withdraw", "Withdraw Certification"),
                            ("special_audit", "Require Special Audit"),
                        ],
                        help_text="Final certification decision",
                        max_length=30,
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(help_text="Justification for the decision"),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_decision",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "certifications_affected",
                    models.ManyToManyField(
                        help_text="Certifications affected by this decision",
                        related_name="certification_decisions",
                        to="core.certification",
                    ),
                ),
                (
                    "decision_maker",
                    models.ForeignKey(
                        help_text="Person making final certification decision",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certification_decisions_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certification Decision",
                "verbose_name_plural": "Certification Decisions",
                "db_table": "audits_certificationdecision",
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint_number", models.CharField(max_length=50, unique=True)),
                ("complainant_name", models.CharField(max_length=255)),
                ("complainant_email", models.EmailField(blank=True, max_length=254)),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("audit_conduct", "Audit Conduct"),
                            ("auditor_behavior", "Auditor Behavior"),
                            ("certification_decision", "Certification Decision"),
                            ("certificate_misuse", "Certificate Misuse"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the complaint"),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("under_investigation", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("escalated", "Escalated to Appeal"),
                        ],
                        default="received",
                        max_length=30,
                    ),
                ),
                (
                    "investigation_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("investigation_notes", models.TextField(blank=True)),
                (
                    "investigation_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("resolution_details", models.TextField(blank=True)),
                ("corrective_actions", models.TextField(blank=True)),
                (
                    "assigned_investigator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_investigating",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to="core.organization",
                    ),
                ),
                (
                    "related_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint",
                "verbose_name_plural": "Complaints",
                "db_table": "audits_complaint",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appeal_number", models.CharField(max_length=50, unique=True)),
                ("appellant_name", models.CharField(max_length=255)),
                ("appellant_email", models.EmailField(blank=True, max_length=254)),
                ("grounds", models.TextField(help_text="Grounds for appeal")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("panel_review", "Panel Review"),
                            ("decided", "Decided"),
                            ("closed", "Closed"),
                        ],
                        default="received",
                        max_length=30,
                    ),
                ),
                (
                    "panel_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upheld", "Upheld"),
                            ("rejected", "Rejected"),
                            ("partially_upheld", "Partially Upheld"),
                        ],
                        max_length=30,
                    ),
                ),
                ("panel_decision_date", models.DateTimeField(blank=True, null=True)),
                ("panel_justification", models.TextField(blank=True)),
                (
                    "panel_members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="appeal_panels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals",
                        to="certification.certificationdecision",
                    ),
                ),
                (
                    "related_complaint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals",
                        to="certification.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appeal",
                "verbose_name_plural": "Appeals",
                "db_table": "audits_appeal",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="TechnicalReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("requires_clarification", "Requires Clarification"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "scope_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Audit scope clearly defined and verified",
                    ),
                ),
                (
                    "objectives_verified",
                    models.BooleanField(
                        default=False, help_text="Audit objectives met"
                    ),
                ),
                (
                    "findings_reviewed",
                    models.BooleanField(
                        default=False,
                        help_text="All findings reviewed and properly documented",
                    ),
                ),
                (
                    "conclusion_clear",
                    models.BooleanField(
                        default=False,
                        help_text="Audit conclusion is clear and justified",
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Technical reviewer's notes"
                    ),
                ),
                (
                    "clarification_requested",
                    models.TextField(
                        blank=True, help_text="Clarifications requested from audit team"
                    ),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="technical_review",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        help_text="CB staff member conducting technical review",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="technical_reviews_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical Review",
                "verbose_name_plural": "Technical Reviews",
                "db_table": "audits_technicalreview",
            },
        ),
        migrations.CreateModel(
            name="TransferCertification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("previous_cb_name", models.CharField(max_length=255)),
                (
                    "previous_cb_accreditation_body",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "previous_certificate_number",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "previous_certificate_issue_date",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "previous_certificate_expiry_date",
                    models.DateField(blank=True, null=True),
                ),
                ("reason_for_transfer", models.TextField(blank=True)),
                ("previous_audit_reports_received", models.BooleanField(default=False)),
                ("previous_nc_records_received", models.BooleanField(default=False)),
                (
                    "previous_surveillance_history_received",
                    models.BooleanField(default=False),
                ),
                (
                    "previous_certificate_file",
                    models.FileField(blank=True, upload_to="transfer_certificates/"),
                ),
                (
                    "previous_audit_reports",
                    models.FileField(
                        blank=True, upload_to="transfer_previous_reports/"
                    ),
                ),
                ("transfer_date_before_expiry", models.BooleanField(default=False)),
                ("no_expiry_extension_applied", models.BooleanField(default=False)),
                ("transfer_approved", models.BooleanField(null=True)),
                ("transfer_approval_notes", models.TextField(blank=True)),
                (
                    "transfer_audit",
                    models.OneToOneField(
                        limit_choices_to={"audit_type": "transfer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_certification",
                        to="audit_management.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Certification",
                "verbose_name_plural": "Transfer Certifications",
                "db_table": "audits_transfercertification",
                "ordering": ["-previous_certificate_expiry_date"],
            },
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["status"], name="audits_comp_status_e0520b_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["complaint_number"], name="audits_comp_complai_d44ae7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(fields=["status"], name="audits_appe_status_6031c3_idx"),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(
                fields=["appeal_number"], name="audits_appe_appeal__dafe87_idx"
            ),
        ),
    ]
