# Generated by Django 5.2.8 on 2025-11-20 18:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("stage1", "Stage 1"),
                            ("stage2", "Stage 2"),
                            ("surveillance", "Surveillance"),
                            ("recertification", "Recertification"),
                            ("transfer", "Transfer"),
                            ("special", "Special"),
                        ],
                        help_text="Type of audit",
                        max_length=20,
                    ),
                ),
                (
                    "total_audit_date_from",
                    models.DateField(help_text="Audit start date"),
                ),
                ("total_audit_date_to", models.DateField(help_text="Audit end date")),
                (
                    "audit_duration_hours",
                    models.FloatField(
                        help_text="Total audit duration in hours",
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("client_review", "Client Review"),
                            ("submitted_to_cb", "Submitted to CB"),
                            ("decided", "Decided"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certifications",
                    models.ManyToManyField(
                        help_text="Certifications covered by this audit",
                        related_name="audits",
                        to="core.certification",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_auditor",
                    models.ForeignKey(
                        help_text="Lead auditor responsible for this audit",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="core.organization",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        help_text="Sites covered by this audit",
                        related_name="audits",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit",
                "verbose_name_plural": "Audits",
                "ordering": ["-total_audit_date_from", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditChanges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_of_name", models.BooleanField(default=False)),
                ("change_of_scope", models.BooleanField(default=False)),
                ("change_of_sites", models.BooleanField(default=False)),
                (
                    "change_of_ms_rep",
                    models.BooleanField(
                        default=False,
                        help_text="Change of Management System Representative",
                    ),
                ),
                ("change_of_signatory", models.BooleanField(default=False)),
                ("change_of_employee_count", models.BooleanField(default=False)),
                ("change_of_contact_info", models.BooleanField(default=False)),
                ("other_has_change", models.BooleanField(default=False)),
                (
                    "other_description",
                    models.TextField(
                        blank=True, help_text="Description of other changes"
                    ),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="audits.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Changes",
                "verbose_name_plural": "Audit Changes",
            },
        ),
        migrations.CreateModel(
            name="AuditPlanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deviations_yes_no",
                    models.BooleanField(
                        default=False,
                        help_text="Were there deviations from the audit plan?",
                    ),
                ),
                (
                    "deviations_details",
                    models.TextField(blank=True, help_text="Details of deviations"),
                ),
                (
                    "issues_affecting_yes_no",
                    models.BooleanField(
                        default=False,
                        help_text="Were there issues affecting the audit?",
                    ),
                ),
                (
                    "issues_affecting_details",
                    models.TextField(
                        blank=True, help_text="Details of issues affecting the audit"
                    ),
                ),
                (
                    "next_audit_date_from",
                    models.DateField(
                        blank=True,
                        help_text="Proposed next audit start date",
                        null=True,
                    ),
                ),
                (
                    "next_audit_date_to",
                    models.DateField(
                        blank=True, help_text="Proposed next audit end date", null=True
                    ),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_review",
                        to="audits.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Plan Review",
                "verbose_name_plural": "Audit Plan Reviews",
            },
        ),
        migrations.CreateModel(
            name="AuditRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("special_audit_required", models.BooleanField(default=False)),
                (
                    "special_audit_details",
                    models.TextField(
                        blank=True, help_text="Details of special audit requirements"
                    ),
                ),
                ("suspension_recommended", models.BooleanField(default=False)),
                (
                    "suspension_certificates",
                    models.TextField(
                        blank=True,
                        help_text="List of certificates to suspend (simple text for now)",
                    ),
                ),
                ("revocation_recommended", models.BooleanField(default=False)),
                (
                    "revocation_certificates",
                    models.TextField(
                        blank=True,
                        help_text="List of certificates to revoke (simple text for now)",
                    ),
                ),
                (
                    "stage2_required",
                    models.BooleanField(
                        default=False, help_text="Stage 2 audit required"
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(blank=True, help_text="Additional decision notes"),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="audits.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Recommendation",
                "verbose_name_plural": "Audit Recommendations",
            },
        ),
        migrations.CreateModel(
            name="AuditSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectives_met", models.BooleanField(default=False)),
                ("objectives_comments", models.TextField(blank=True)),
                ("scope_appropriate", models.BooleanField(default=False)),
                ("scope_comments", models.TextField(blank=True)),
                (
                    "ms_meets_requirements",
                    models.BooleanField(
                        default=False, help_text="Management system meets requirements"
                    ),
                ),
                ("ms_comments", models.TextField(blank=True)),
                ("management_review_effective", models.BooleanField(default=False)),
                ("management_review_comments", models.TextField(blank=True)),
                ("internal_audit_effective", models.BooleanField(default=False)),
                ("internal_audit_comments", models.TextField(blank=True)),
                (
                    "ms_effective",
                    models.BooleanField(
                        default=False, help_text="Management system is effective"
                    ),
                ),
                ("ms_effective_comments", models.TextField(blank=True)),
                ("correct_use_of_logos", models.BooleanField(default=False)),
                ("logos_comments", models.TextField(blank=True)),
                ("promoted_to_committee", models.BooleanField(default=False)),
                ("committee_comments", models.TextField(blank=True)),
                (
                    "general_commentary",
                    models.TextField(blank=True, help_text="General commentary (A.4)"),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="audits.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Summary",
                "verbose_name_plural": "Audit Summaries",
            },
        ),
        migrations.CreateModel(
            name="AuditTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (required if user is null)", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Job title or role", max_length=255
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead_auditor", "Lead Auditor"),
                            ("auditor", "Auditor"),
                            ("technical_expert", "Technical Expert"),
                            ("trainee", "Trainee"),
                            ("observer", "Observer"),
                        ],
                        help_text="Role in the audit team",
                        max_length=20,
                    ),
                ),
                (
                    "date_from",
                    models.DateField(help_text="Start date for this team member"),
                ),
                (
                    "date_to",
                    models.DateField(help_text="End date for this team member"),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="audits.audit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account (null for external experts)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Team Member",
                "verbose_name_plural": "Audit Team Members",
                "ordering": ["audit", "role", "name"],
            },
        ),
        migrations.CreateModel(
            name="Nonconformity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clause",
                    models.CharField(
                        help_text="Clause reference (e.g., '4.1', '7.5.1')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("major", "Major"), ("minor", "Minor")],
                        help_text="Major or minor nonconformity",
                        max_length=10,
                    ),
                ),
                (
                    "objective_evidence",
                    models.TextField(
                        help_text="Objective evidence of the nonconformity"
                    ),
                ),
                (
                    "statement_of_nc",
                    models.TextField(help_text="Statement of the nonconformity"),
                ),
                (
                    "auditor_explanation",
                    models.TextField(help_text="Auditor's explanation"),
                ),
                (
                    "client_root_cause",
                    models.TextField(
                        blank=True, help_text="Client's root cause analysis"
                    ),
                ),
                (
                    "client_correction",
                    models.TextField(
                        blank=True, help_text="Client's immediate correction"
                    ),
                ),
                (
                    "client_corrective_action",
                    models.TextField(
                        blank=True, help_text="Client's corrective action plan"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date for corrective action",
                        null=True,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("client_responded", "Client Responded"),
                            ("accepted", "Accepted"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="audits.audit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        blank=True,
                        help_text="Standard clause this finding relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.standard",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ncs_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nonconformity",
                "verbose_name_plural": "Nonconformities",
                "ordering": ["category", "clause", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload evidence file", upload_to="evidence/%Y/%m/%d/"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="audits.audit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: link to a specific nonconformity",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="audits.nonconformity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence File",
                "verbose_name_plural": "Evidence Files",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clause",
                    models.CharField(
                        help_text="Clause reference (e.g., '4.1', '7.5.1')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("statement", models.TextField(help_text="Observation statement")),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Additional explanation"),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="audits.audit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        blank=True,
                        help_text="Standard clause this finding relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observation",
                "verbose_name_plural": "Observations",
            },
        ),
        migrations.CreateModel(
            name="OpportunityForImprovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clause",
                    models.CharField(
                        help_text="Clause reference (e.g., '4.1', '7.5.1')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(help_text="Description of the opportunity"),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="audits.audit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        blank=True,
                        help_text="Standard clause this finding relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity for Improvement",
                "verbose_name_plural": "Opportunities for Improvement",
            },
        ),
    ]
