# Generated by Django 5.2.8 on 2025-11-20 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "audits",
            "0003_auditstatuslog_certificationdecision_technicalreview_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RootCauseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Resource inadequacy')",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this category (e.g., 'RC-001')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of this root cause category",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is currently in use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchical organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="audits.rootcausecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Root Cause Category",
                "verbose_name_plural": "Root Cause Categories",
                "ordering": ["code", "name"],
            },
        ),
        migrations.AddField(
            model_name="nonconformity",
            name="root_cause_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Root cause categories for systematic analysis",
                related_name="nonconformities",
                to="audits.rootcausecategory",
            ),
        ),
        migrations.CreateModel(
            name="AuditorCompetenceWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warning_type",
                    models.CharField(
                        choices=[
                            ("scope_mismatch", "Scope Mismatch"),
                            ("insufficient_experience", "Insufficient Experience"),
                            ("expired_qualification", "Expired Qualification"),
                            ("language_barrier", "Language Barrier"),
                            ("conflict_of_interest", "Conflict of Interest"),
                            ("other", "Other"),
                        ],
                        help_text="Type of competence warning",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Severity level of the warning",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the competence issue"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this warning was issued"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this warning was resolved",
                        null=True,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="How this warning was resolved"
                    ),
                ),
                (
                    "acknowledged_by_auditor",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the auditor has acknowledged this warning",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        help_text="Audit this warning relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competence_warnings",
                        to="audits.audit",
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        help_text="Auditor this warning is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competence_warnings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="CB staff member who issued this warning",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competence_warnings_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditor Competence Warning",
                "verbose_name_plural": "Auditor Competence Warnings",
                "ordering": ["-issued_at", "-severity"],
                "indexes": [
                    models.Index(
                        fields=["audit", "auditor"],
                        name="audits_audi_audit_i_a393a7_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="audits_audi_severit_8e96d2_idx"
                    ),
                    models.Index(
                        fields=["resolved_at"], name="audits_audi_resolve_a8fca0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FindingRecurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of times this issue has recurred"
                    ),
                ),
                (
                    "first_occurrence",
                    models.DateField(
                        help_text="Date of first occurrence of this finding"
                    ),
                ),
                (
                    "last_occurrence",
                    models.DateField(help_text="Date of most recent occurrence"),
                ),
                (
                    "previous_audits",
                    models.TextField(
                        blank=True,
                        help_text="References to previous audits where this issue was found",
                    ),
                ),
                (
                    "corrective_actions_effective",
                    models.BooleanField(
                        default=False,
                        help_text="Whether previous corrective actions were effective",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on resolution attempts and outcomes",
                    ),
                ),
                (
                    "escalation_required",
                    models.BooleanField(
                        default=False,
                        help_text="Flag for findings requiring management attention",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finding",
                    models.OneToOneField(
                        help_text="The finding this recurrence data relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_data",
                        to="audits.nonconformity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finding Recurrence",
                "verbose_name_plural": "Finding Recurrences",
                "ordering": ["-recurrence_count", "-last_occurrence"],
                "indexes": [
                    models.Index(
                        fields=["recurrence_count"],
                        name="audits_find_recurre_2bc22d_idx",
                    ),
                    models.Index(
                        fields=["escalation_required"],
                        name="audits_find_escalat_8781e8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="rootcausecategory",
            index=models.Index(fields=["code"], name="audits_root_code_ba18ac_idx"),
        ),
        migrations.AddIndex(
            model_name="rootcausecategory",
            index=models.Index(
                fields=["is_active"], name="audits_root_is_acti_81937c_idx"
            ),
        ),
    ]
