# Generated by Django 5.2.8 on 2025-11-21 13:35
# Sprint 8, Task 8.7: Performance optimization indexes

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0005_add_performance_indexes"),
    ]

    operations = [
        # Audit indexes for common queries
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["organization", "status"], name="audits_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["lead_auditor", "status"], name="audits_auditor_status_idx"),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["status", "total_audit_date_from"], name="audits_status_date_idx"),
        ),
        # Finding indexes for verification queries
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(fields=["audit", "verification_status"], name="nc_audit_status_idx"),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(fields=["audit", "category"], name="nc_audit_category_idx"),
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(fields=["audit", "created_at"], name="obs_audit_date_idx"),
        ),
        migrations.AddIndex(
            model_name="opportunityforimprovement",
            index=models.Index(fields=["audit", "created_at"], name="ofi_audit_date_idx"),
        ),
    ]
