# Generated by Django 5.2.8 on 2025-11-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0006_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="audit",
            name="audits_org_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="audit",
            name="audits_auditor_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="audit",
            name="audits_status_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="nonconformity",
            name="nc_audit_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="nonconformity",
            name="nc_audit_category_idx",
        ),
        migrations.RemoveIndex(
            model_name="observation",
            name="obs_audit_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="opportunityforimprovement",
            name="ofi_audit_date_idx",
        ),
        migrations.AlterField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("report_draft", "Report Draft"),
                    ("client_review", "Client Review"),
                    ("submitted", "Submitted"),
                    ("decided", "Decided"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
    ]
