# Generated by Django 5.2.8 on 2025-11-24 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0008_migrate_old_status_values"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("complaint_number", models.CharField(max_length=50, unique=True)),
                ("complainant_name", models.CharField(max_length=255)),
                ("complainant_email", models.EmailField(blank=True, max_length=254)),
                (
                    "complaint_type",
                    models.CharField(
                        choices=[
                            ("audit_conduct", "Audit Conduct"),
                            ("auditor_behavior", "Auditor Behavior"),
                            ("certification_decision", "Certification Decision"),
                            ("certificate_misuse", "Certificate Misuse"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("description", models.TextField(help_text="Detailed description of the complaint")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("under_investigation", "Under Investigation"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("escalated", "Escalated to Appeal"),
                        ],
                        default="received",
                        max_length=30,
                    ),
                ),
                ("investigation_started_at", models.DateTimeField(blank=True, null=True)),
                ("investigation_notes", models.TextField(blank=True)),
                ("investigation_completed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_details", models.TextField(blank=True)),
                ("corrective_actions", models.TextField(blank=True)),
                (
                    "assigned_investigator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_investigating",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to="core.organization",
                    ),
                ),
                (
                    "related_audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints",
                        to="audits.audit",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="complaints_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Complaint",
                "verbose_name_plural": "Complaints",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Appeal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("appeal_number", models.CharField(max_length=50, unique=True)),
                ("appellant_name", models.CharField(max_length=255)),
                ("appellant_email", models.EmailField(blank=True, max_length=254)),
                ("grounds", models.TextField(help_text="Grounds for appeal")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("panel_review", "Panel Review"),
                            ("decided", "Decided"),
                            ("closed", "Closed"),
                        ],
                        default="received",
                        max_length=30,
                    ),
                ),
                (
                    "panel_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upheld", "Upheld"),
                            ("rejected", "Rejected"),
                            ("partially_upheld", "Partially Upheld"),
                        ],
                        max_length=30,
                    ),
                ),
                ("panel_decision_date", models.DateTimeField(blank=True, null=True)),
                ("panel_justification", models.TextField(blank=True)),
                (
                    "panel_members",
                    models.ManyToManyField(blank=True, related_name="appeal_panels", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "related_decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals",
                        to="audits.certificationdecision",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_complaint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appeals",
                        to="audits.complaint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appeal",
                "verbose_name_plural": "Appeals",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="PreAuditDocumentSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("quality_manual", "Quality Manual"),
                            ("procedure", "Procedure"),
                            ("work_instruction", "Work Instruction"),
                            ("record", "Record/Form"),
                            ("org_chart", "Organization Chart"),
                            ("scope_statement", "Scope Statement"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("document_file", models.FileField(upload_to="pre_audit_docs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_by_auditor", models.BooleanField(default=False)),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_audit_documents",
                        to="audits.audit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pre_audit_docs_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Audit Document Submission",
                "verbose_name_plural": "Pre-Audit Document Submissions",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RemoteAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("video_conference", "Video Conference"),
                            ("document_review_remote", "Remote Document Review"),
                            ("screen_sharing", "Screen Sharing"),
                            ("remote_access", "Remote System Access"),
                            ("electronic_signature", "Electronic Signature"),
                        ],
                        max_length=40,
                    ),
                ),
                ("client_participants", models.TextField(blank=True, help_text="Names/roles of client participants")),
                (
                    "platform_used",
                    models.CharField(help_text="Technology platform (Zoom/Teams/WebEx/etc.)", max_length=100),
                ),
                ("session_start", models.DateTimeField()),
                ("session_end", models.DateTimeField()),
                ("technology_validated", models.BooleanField(default=False)),
                ("security_controls_verified", models.BooleanField(default=False)),
                ("data_protection_confirmed", models.BooleanField(default=False)),
                ("session_notes", models.TextField(blank=True)),
                ("technical_issues", models.TextField(blank=True)),
                ("recording_file", models.FileField(blank=True, upload_to="remote_audit_recordings/")),
                (
                    "site_visit_complement",
                    models.BooleanField(
                        default=False, help_text="Was an on-site component also performed as complement?"
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="remote_logs", to="audits.audit"
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remote_audit_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Audit Log",
                "verbose_name_plural": "Remote Audit Logs",
                "ordering": ["-session_start"],
            },
        ),
        migrations.CreateModel(
            name="TransferCertification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("previous_cb_name", models.CharField(max_length=255)),
                ("previous_cb_accreditation_body", models.CharField(blank=True, max_length=255)),
                ("previous_certificate_number", models.CharField(blank=True, max_length=100)),
                ("previous_certificate_issue_date", models.DateField(blank=True, null=True)),
                ("previous_certificate_expiry_date", models.DateField(blank=True, null=True)),
                ("reason_for_transfer", models.TextField(blank=True)),
                ("previous_audit_reports_received", models.BooleanField(default=False)),
                ("previous_nc_records_received", models.BooleanField(default=False)),
                ("previous_surveillance_history_received", models.BooleanField(default=False)),
                ("previous_certificate_file", models.FileField(blank=True, upload_to="transfer_certificates/")),
                ("previous_audit_reports", models.FileField(blank=True, upload_to="transfer_previous_reports/")),
                ("transfer_date_before_expiry", models.BooleanField(default=False)),
                ("no_expiry_extension_applied", models.BooleanField(default=False)),
                ("transfer_approved", models.BooleanField(null=True)),
                ("transfer_approval_notes", models.TextField(blank=True)),
                (
                    "transfer_audit",
                    models.OneToOneField(
                        limit_choices_to={"audit_type": "transfer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_certification",
                        to="audits.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Certification",
                "verbose_name_plural": "Transfer Certifications",
                "ordering": ["-previous_certificate_expiry_date"],
            },
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["status"], name="audits_comp_status_e0520b_idx"),
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(fields=["complaint_number"], name="audits_comp_complai_d44ae7_idx"),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(fields=["status"], name="audits_appe_status_6031c3_idx"),
        ),
        migrations.AddIndex(
            model_name="appeal",
            index=models.Index(fields=["appeal_number"], name="audits_appe_appeal__dafe87_idx"),
        ),
        migrations.AddIndex(
            model_name="preauditdocumentsubmission",
            index=models.Index(fields=["audit", "uploaded_at"], name="audits_prea_audit_i_bad215_idx"),
        ),
        migrations.AddIndex(
            model_name="remoteauditlog",
            index=models.Index(fields=["audit", "session_start"], name="audits_remo_audit_i_b2be06_idx"),
        ),
    ]
