# Generated by Django 5.2.8 on 2025-11-25 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0009_complaint_appeal_preauditdocumentsubmission_and_more"),
        ("core", "0002_surveillanceschedule_certificatehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="audit_type",
            field=models.CharField(
                choices=[
                    ("stage1", "Stage 1"),
                    ("stage2", "Stage 2"),
                    ("surveillance", "Surveillance"),
                    ("recertification", "Recertification"),
                    ("transfer", "Transfer"),
                    ("special", "Special"),
                    ("internal", "Internal Audit"),
                ],
                help_text="Type of audit",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("scheduled", "Scheduled"),
                    ("in_progress", "In Progress"),
                    ("report_draft", "Report Draft"),
                    ("client_review", "Client Review"),
                    ("submitted", "Submitted"),
                    ("technical_review", "Technical Review"),
                    ("decision_pending", "Decision Pending"),
                    ("decided", "Decided"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AuditProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Program title (e.g., '2025 Internal Audit Program')", max_length=255),
                ),
                ("year", models.PositiveIntegerField(help_text="Program year")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("objectives", models.TextField(help_text="Audit program objectives (ISO 19011 5.2)")),
                (
                    "risks_opportunities",
                    models.TextField(
                        help_text="Risks and opportunities associated with the audit program (ISO 19011 5.3)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_programs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_programs",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Program",
                "verbose_name_plural": "Audit Programs",
                "ordering": ["-year", "title"],
                "unique_together": {("organization", "year", "title")},
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Audit program this audit belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audits",
                to="audits.auditprogram",
            ),
        ),
    ]
