# Generated by Django 6.0 on 2025-12-03 20:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("stage1", "Stage 1"),
                            ("stage2", "Stage 2"),
                            ("surveillance", "Surveillance"),
                            ("recertification", "Recertification"),
                            ("transfer", "Transfer"),
                            ("special", "Special"),
                            ("internal", "Internal Audit"),
                        ],
                        help_text="Type of audit",
                        max_length=20,
                    ),
                ),
                (
                    "total_audit_date_from",
                    models.DateField(help_text="Audit start date"),
                ),
                ("total_audit_date_to", models.DateField(help_text="Audit end date")),
                (
                    "planned_duration_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Planned audit duration (IAF MD5 calculation)",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "actual_duration_hours",
                    models.FloatField(
                        blank=True,
                        help_text="Actual audit duration in hours",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "duration_justification",
                    models.TextField(
                        blank=True,
                        help_text="Justification for deviation from planned duration (IAF MD5)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("report_draft", "Report Draft"),
                            ("client_review", "Client Review"),
                            ("submitted", "Submitted"),
                            ("technical_review", "Technical Review"),
                            ("decision_pending", "Decision Pending"),
                            ("decided", "Decided"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certifications",
                    models.ManyToManyField(
                        help_text="Certifications covered by this audit",
                        related_name="audits",
                        to="core.certification",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead_auditor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lead auditor responsible for this audit",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audits_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audits",
                        to="core.organization",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        help_text="Sites covered by this audit",
                        related_name="audits",
                        to="core.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit",
                "verbose_name_plural": "Audits",
                "db_table": "audits_audit",
                "ordering": ["-total_audit_date_from", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditChanges",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("change_of_name", models.BooleanField(default=False)),
                ("change_of_scope", models.BooleanField(default=False)),
                ("change_of_sites", models.BooleanField(default=False)),
                (
                    "change_of_ms_rep",
                    models.BooleanField(
                        default=False,
                        help_text="Change of Management System Representative",
                    ),
                ),
                ("change_of_signatory", models.BooleanField(default=False)),
                ("change_of_employee_count", models.BooleanField(default=False)),
                ("change_of_contact_info", models.BooleanField(default=False)),
                ("other_has_change", models.BooleanField(default=False)),
                (
                    "other_description",
                    models.TextField(
                        blank=True, help_text="Description of other changes"
                    ),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="audit_management.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Changes",
                "verbose_name_plural": "Audit Changes",
                "db_table": "audits_auditchanges",
            },
        ),
        migrations.CreateModel(
            name="AuditPlanReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deviations_yes_no",
                    models.BooleanField(
                        default=False,
                        help_text="Were there deviations from the audit plan?",
                    ),
                ),
                (
                    "deviations_details",
                    models.TextField(blank=True, help_text="Details of deviations"),
                ),
                (
                    "issues_affecting_yes_no",
                    models.BooleanField(
                        default=False,
                        help_text="Were there issues affecting the audit?",
                    ),
                ),
                (
                    "issues_affecting_details",
                    models.TextField(
                        blank=True, help_text="Details of issues affecting the audit"
                    ),
                ),
                (
                    "next_audit_date_from",
                    models.DateField(
                        blank=True,
                        help_text="Proposed next audit start date",
                        null=True,
                    ),
                ),
                (
                    "next_audit_date_to",
                    models.DateField(
                        blank=True, help_text="Proposed next audit end date", null=True
                    ),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_review",
                        to="audit_management.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Plan Review",
                "verbose_name_plural": "Audit Plan Reviews",
                "db_table": "audits_auditplanreview",
            },
        ),
        migrations.CreateModel(
            name="AuditProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Program title (e.g., '2025 Internal Audit Program')",
                        max_length=255,
                    ),
                ),
                ("year", models.PositiveIntegerField(help_text="Program year")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        help_text="Audit program objectives (ISO 19011 5.2)"
                    ),
                ),
                (
                    "risks_opportunities",
                    models.TextField(
                        help_text="Risks and opportunities associated with the audit program (ISO 19011 5.3)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_programs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_programs",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Program",
                "verbose_name_plural": "Audit Programs",
                "db_table": "audits_auditprogram",
                "ordering": ["-year", "title"],
                "unique_together": {("organization", "year", "title")},
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="program",
            field=models.ForeignKey(
                blank=True,
                help_text="Audit program this audit belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audits",
                to="audit_management.auditprogram",
            ),
        ),
        migrations.CreateModel(
            name="AuditRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("special_audit_required", models.BooleanField(default=False)),
                (
                    "special_audit_details",
                    models.TextField(
                        blank=True, help_text="Details of special audit requirements"
                    ),
                ),
                ("suspension_recommended", models.BooleanField(default=False)),
                (
                    "suspension_certificates",
                    models.TextField(
                        blank=True,
                        help_text="List of certificates to suspend (simple text for now)",
                    ),
                ),
                ("revocation_recommended", models.BooleanField(default=False)),
                (
                    "revocation_certificates",
                    models.TextField(
                        blank=True,
                        help_text="List of certificates to revoke (simple text for now)",
                    ),
                ),
                (
                    "stage2_required",
                    models.BooleanField(
                        default=False, help_text="Stage 2 audit required"
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(blank=True, help_text="Additional decision notes"),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation",
                        to="audit_management.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Recommendation",
                "verbose_name_plural": "Audit Recommendations",
                "db_table": "audits_auditrecommendation",
            },
        ),
        migrations.CreateModel(
            name="AuditStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(help_text="Previous status", max_length=30),
                ),
                ("to_status", models.CharField(help_text="New status", max_length=30)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this transition"
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Status Log",
                "verbose_name_plural": "Audit Status Logs",
                "db_table": "audits_auditstatuslog",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("objectives_met", models.BooleanField(default=False)),
                ("objectives_comments", models.TextField(blank=True)),
                ("scope_appropriate", models.BooleanField(default=False)),
                ("scope_comments", models.TextField(blank=True)),
                (
                    "ms_meets_requirements",
                    models.BooleanField(
                        default=False, help_text="Management system meets requirements"
                    ),
                ),
                ("ms_comments", models.TextField(blank=True)),
                ("management_review_effective", models.BooleanField(default=False)),
                ("management_review_comments", models.TextField(blank=True)),
                ("internal_audit_effective", models.BooleanField(default=False)),
                ("internal_audit_comments", models.TextField(blank=True)),
                (
                    "ms_effective",
                    models.BooleanField(
                        default=False, help_text="Management system is effective"
                    ),
                ),
                ("ms_effective_comments", models.TextField(blank=True)),
                ("correct_use_of_logos", models.BooleanField(default=False)),
                ("logos_comments", models.TextField(blank=True)),
                ("promoted_to_committee", models.BooleanField(default=False)),
                ("committee_comments", models.TextField(blank=True)),
                (
                    "general_commentary",
                    models.TextField(blank=True, help_text="General commentary (A.4)"),
                ),
                (
                    "audit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summary",
                        to="audit_management.audit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Summary",
                "verbose_name_plural": "Audit Summaries",
                "db_table": "audits_auditsummary",
            },
        ),
        migrations.CreateModel(
            name="AuditTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name (required if user is null)", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="Job title or role", max_length=255
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("lead_auditor", "Lead Auditor"),
                            ("auditor", "Auditor"),
                            ("technical_expert", "Technical Expert"),
                            ("trainee", "Trainee"),
                            ("observer", "Observer"),
                        ],
                        help_text="Role in the audit team",
                        max_length=20,
                    ),
                ),
                (
                    "date_from",
                    models.DateField(help_text="Start date for this team member"),
                ),
                (
                    "date_to",
                    models.DateField(help_text="End date for this team member"),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account (null for external experts)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Team Member",
                "verbose_name_plural": "Audit Team Members",
                "db_table": "audits_auditteammember",
                "ordering": ["audit", "role", "name"],
            },
        ),
        migrations.CreateModel(
            name="Nonconformity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clause",
                    models.CharField(
                        help_text="Clause reference (e.g., '4.1', '7.5.1')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("major", "Major"), ("minor", "Minor")],
                        help_text="Major or minor nonconformity",
                        max_length=10,
                    ),
                ),
                (
                    "objective_evidence",
                    models.TextField(
                        help_text="Objective evidence of the nonconformity"
                    ),
                ),
                (
                    "statement_of_nc",
                    models.TextField(help_text="Statement of the nonconformity"),
                ),
                (
                    "auditor_explanation",
                    models.TextField(help_text="Auditor's explanation"),
                ),
                (
                    "client_root_cause",
                    models.TextField(
                        blank=True, help_text="Client's root cause analysis"
                    ),
                ),
                (
                    "client_correction",
                    models.TextField(
                        blank=True, help_text="Client's immediate correction"
                    ),
                ),
                (
                    "client_corrective_action",
                    models.TextField(
                        blank=True, help_text="Client's corrective action plan"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        help_text="Due date for corrective action",
                        null=True,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("client_responded", "Client Responded"),
                            ("accepted", "Accepted"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes from the auditor during verification",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific site where finding was raised (for multi-site audits)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_findings",
                        to="core.site",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        blank=True,
                        help_text="Standard clause this finding relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.standard",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ncs_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Nonconformity",
                "verbose_name_plural": "Nonconformities",
                "db_table": "audits_nonconformity",
                "ordering": ["category", "clause", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="FindingRecurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence_count",
                    models.PositiveIntegerField(
                        default=1, help_text="Number of times this issue has recurred"
                    ),
                ),
                (
                    "first_occurrence",
                    models.DateField(
                        help_text="Date of first occurrence of this finding"
                    ),
                ),
                (
                    "last_occurrence",
                    models.DateField(help_text="Date of most recent occurrence"),
                ),
                (
                    "previous_audits",
                    models.TextField(
                        blank=True,
                        help_text="References to previous audits where this issue was found",
                    ),
                ),
                (
                    "corrective_actions_effective",
                    models.BooleanField(
                        default=False,
                        help_text="Whether previous corrective actions were effective",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes on resolution attempts and outcomes",
                    ),
                ),
                (
                    "escalation_required",
                    models.BooleanField(
                        default=False,
                        help_text="Flag for findings requiring management attention",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finding",
                    models.OneToOneField(
                        help_text="The finding this recurrence data relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurrence_data",
                        to="audit_management.nonconformity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finding Recurrence",
                "verbose_name_plural": "Finding Recurrences",
                "db_table": "audits_findingrecurrence",
                "ordering": ["-recurrence_count", "-last_occurrence"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Upload evidence file", upload_to="evidence/%Y/%m/%d/"
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("document", "Document Review"),
                            ("interview", "Interview Notes"),
                            ("observation", "Direct Observation"),
                            ("record", "Record Examination"),
                            ("photo", "Photographic Evidence"),
                            ("other", "Other"),
                        ],
                        default="document",
                        help_text="Type of audit evidence",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the evidence"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "retention_years",
                    models.PositiveIntegerField(
                        default=7, help_text="Number of years to retain this evidence"
                    ),
                ),
                (
                    "purge_after",
                    models.DateField(
                        blank=True,
                        help_text="Date when this evidence should be purged (auto-calculated)",
                        null=True,
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finding",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: link to a specific nonconformity",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_files",
                        to="audit_management.nonconformity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence File",
                "verbose_name_plural": "Evidence Files",
                "db_table": "audits_evidencefile",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clause",
                    models.CharField(
                        help_text="Clause reference (e.g., '4.1', '7.5.1')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("statement", models.TextField(help_text="Observation statement")),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Additional explanation"),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific site where finding was raised (for multi-site audits)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_findings",
                        to="core.site",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        blank=True,
                        help_text="Standard clause this finding relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observation",
                "verbose_name_plural": "Observations",
                "db_table": "audits_observation",
            },
        ),
        migrations.CreateModel(
            name="OpportunityForImprovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clause",
                    models.CharField(
                        help_text="Clause reference (e.g., '4.1', '7.5.1')",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(help_text="Description of the opportunity"),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific site where finding was raised (for multi-site audits)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_findings",
                        to="core.site",
                    ),
                ),
                (
                    "standard",
                    models.ForeignKey(
                        blank=True,
                        help_text="Standard clause this finding relates to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.standard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opportunity for Improvement",
                "verbose_name_plural": "Opportunities for Improvement",
                "db_table": "audits_opportunityforimprovement",
            },
        ),
        migrations.CreateModel(
            name="PreAuditDocumentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("quality_manual", "Quality Manual"),
                            ("procedure", "Procedure"),
                            ("work_instruction", "Work Instruction"),
                            ("record", "Record/Form"),
                            ("org_chart", "Organization Chart"),
                            ("scope_statement", "Scope Statement"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("document_file", models.FileField(upload_to="pre_audit_docs/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_by_auditor", models.BooleanField(default=False)),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_audit_documents",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pre_audit_docs_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pre-Audit Document Submission",
                "verbose_name_plural": "Pre-Audit Document Submissions",
                "db_table": "audits_preauditdocumentsubmission",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="RemoteAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("video_conference", "Video Conference"),
                            ("document_review_remote", "Remote Document Review"),
                            ("screen_sharing", "Screen Sharing"),
                            ("remote_access", "Remote System Access"),
                            ("electronic_signature", "Electronic Signature"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "client_participants",
                    models.TextField(
                        blank=True, help_text="Names/roles of client participants"
                    ),
                ),
                (
                    "platform_used",
                    models.CharField(
                        help_text="Technology platform (Zoom/Teams/WebEx/etc.)",
                        max_length=100,
                    ),
                ),
                ("session_start", models.DateTimeField()),
                ("session_end", models.DateTimeField()),
                ("technology_validated", models.BooleanField(default=False)),
                ("security_controls_verified", models.BooleanField(default=False)),
                ("data_protection_confirmed", models.BooleanField(default=False)),
                ("session_notes", models.TextField(blank=True)),
                ("technical_issues", models.TextField(blank=True)),
                (
                    "recording_file",
                    models.FileField(blank=True, upload_to="remote_audit_recordings/"),
                ),
                (
                    "site_visit_complement",
                    models.BooleanField(
                        default=False,
                        help_text="Was an on-site component also performed as complement?",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="remote_logs",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remote_audit_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Remote Audit Log",
                "verbose_name_plural": "Remote Audit Logs",
                "db_table": "audits_remoteauditlog",
                "ordering": ["-session_start"],
            },
        ),
        migrations.CreateModel(
            name="RootCauseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'Resource inadequacy')",
                        max_length=255,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this category (e.g., 'RC-001')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of this root cause category",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this category is currently in use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category for hierarchical organization",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="audit_management.rootcausecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Root Cause Category",
                "verbose_name_plural": "Root Cause Categories",
                "db_table": "audits_rootcausecategory",
                "ordering": ["code", "name"],
            },
        ),
        migrations.AddField(
            model_name="nonconformity",
            name="root_cause_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Root cause categories for systematic analysis",
                related_name="nonconformities",
                to="audit_management.rootcausecategory",
            ),
        ),
        migrations.CreateModel(
            name="AuditorCompetenceWarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warning_type",
                    models.CharField(
                        choices=[
                            ("scope_mismatch", "Scope Mismatch"),
                            ("insufficient_experience", "Insufficient Experience"),
                            ("expired_qualification", "Expired Qualification"),
                            ("language_barrier", "Language Barrier"),
                            ("conflict_of_interest", "Conflict of Interest"),
                            ("other", "Other"),
                        ],
                        help_text="Type of competence warning",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Severity level of the warning",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the competence issue"
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this warning was issued"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this warning was resolved",
                        null=True,
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True, help_text="How this warning was resolved"
                    ),
                ),
                (
                    "acknowledged_by_auditor",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the auditor has acknowledged this warning",
                    ),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        help_text="Audit this warning relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competence_warnings",
                        to="audit_management.audit",
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        help_text="Auditor this warning is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competence_warnings_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="CB staff member who issued this warning",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competence_warnings_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Auditor Competence Warning",
                "verbose_name_plural": "Auditor Competence Warnings",
                "db_table": "audits_auditorcompetencewarning",
                "ordering": ["-issued_at", "-severity"],
                "indexes": [
                    models.Index(
                        fields=["audit", "auditor"],
                        name="audits_audi_audit_i_a393a7_idx",
                    ),
                    models.Index(
                        fields=["severity"], name="audits_audi_severit_8e96d2_idx"
                    ),
                    models.Index(
                        fields=["resolved_at"], name="audits_audi_resolve_a8fca0_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["status"], name="audits_audi_status_2432b1_idx"),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["organization", "status"], name="audits_audi_organiz_eccc28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["lead_auditor"], name="audits_audi_lead_au_563392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditstatuslog",
            index=models.Index(
                fields=["audit", "-changed_at"], name="audits_audi_audit_i_57d946_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="findingrecurrence",
            index=models.Index(
                fields=["recurrence_count"], name="audits_find_recurre_2bc22d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="findingrecurrence",
            index=models.Index(
                fields=["escalation_required"], name="audits_find_escalat_8781e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidencefile",
            index=models.Index(
                fields=["purge_after"], name="audits_evid_purge_a_b1f53c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="preauditdocumentsubmission",
            index=models.Index(
                fields=["audit", "uploaded_at"], name="audits_prea_audit_i_bad215_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="remoteauditlog",
            index=models.Index(
                fields=["audit", "session_start"], name="audits_remo_audit_i_b2be06_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rootcausecategory",
            index=models.Index(fields=["code"], name="audits_root_code_ba18ac_idx"),
        ),
        migrations.AddIndex(
            model_name="rootcausecategory",
            index=models.Index(
                fields=["is_active"], name="audits_root_is_acti_81937c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["verification_status"], name="audits_nonc_verific_f7dc33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["audit", "verification_status"],
                name="audits_nonc_audit_i_e1374b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["category", "verification_status"],
                name="audits_nonc_categor_21a925_idx",
            ),
        ),
    ]
