# Generated by Django 5.2.8 on 2025-11-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonconformity",
            name="verification_notes",
            field=models.TextField(
                blank=True, help_text="Notes from the auditor during verification"
            ),
        ),
    ]
