# Generated by Django 5.2.8 on 2025-11-20 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0002_nonconformity_verification_notes"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(help_text="Previous status", max_length=30),
                ),
                ("to_status", models.CharField(help_text="New status", max_length=30)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this transition"
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Status Log",
                "verbose_name_plural": "Audit Status Logs",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="CertificationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("grant", "Grant Certification"),
                            ("refuse", "Refuse Certification"),
                            ("suspend", "Suspend Certification"),
                            ("withdraw", "Withdraw Certification"),
                            ("special_audit", "Require Special Audit"),
                        ],
                        help_text="Final certification decision",
                        max_length=30,
                    ),
                ),
                (
                    "decision_notes",
                    models.TextField(help_text="Justification for the decision"),
                ),
            ],
            options={
                "verbose_name": "Certification Decision",
                "verbose_name_plural": "Certification Decisions",
            },
        ),
        migrations.CreateModel(
            name="TechnicalReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("requires_clarification", "Requires Clarification"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "scope_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Audit scope clearly defined and verified",
                    ),
                ),
                (
                    "objectives_verified",
                    models.BooleanField(
                        default=False, help_text="Audit objectives met"
                    ),
                ),
                (
                    "findings_reviewed",
                    models.BooleanField(
                        default=False,
                        help_text="All findings reviewed and properly documented",
                    ),
                ),
                (
                    "conclusion_clear",
                    models.BooleanField(
                        default=False,
                        help_text="Audit conclusion is clear and justified",
                    ),
                ),
                (
                    "reviewer_notes",
                    models.TextField(
                        blank=True, help_text="Technical reviewer's notes"
                    ),
                ),
                (
                    "clarification_requested",
                    models.TextField(
                        blank=True, help_text="Clarifications requested from audit team"
                    ),
                ),
            ],
            options={
                "verbose_name": "Technical Review",
                "verbose_name_plural": "Technical Reviews",
            },
        ),
        migrations.RemoveField(
            model_name="audit",
            name="audit_duration_hours",
        ),
        migrations.AddField(
            model_name="audit",
            name="actual_duration_hours",
            field=models.FloatField(
                blank=True,
                help_text="Actual audit duration in hours",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="duration_justification",
            field=models.TextField(
                blank=True,
                help_text="Justification for deviation from planned duration (IAF MD5)",
            ),
        ),
        migrations.AddField(
            model_name="audit",
            name="planned_duration_hours",
            field=models.FloatField(
                blank=True,
                help_text="Planned audit duration (IAF MD5 calculation)",
                null=True,
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="description",
            field=models.TextField(blank=True, help_text="Description of the evidence"),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="evidence_type",
            field=models.CharField(
                choices=[
                    ("document", "Document Review"),
                    ("interview", "Interview Notes"),
                    ("observation", "Direct Observation"),
                    ("record", "Record Examination"),
                    ("photo", "Photographic Evidence"),
                    ("other", "Other"),
                ],
                default="document",
                help_text="Type of audit evidence",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="purge_after",
            field=models.DateField(
                blank=True,
                help_text="Date when this evidence should be purged (auto-calculated)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="retention_years",
            field=models.PositiveIntegerField(
                default=7, help_text="Number of years to retain this evidence"
            ),
        ),
        migrations.AddField(
            model_name="nonconformity",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific site where finding was raised (for multi-site audits)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_findings",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="observation",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific site where finding was raised (for multi-site audits)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_findings",
                to="core.site",
            ),
        ),
        migrations.AddField(
            model_name="opportunityforimprovement",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific site where finding was raised (for multi-site audits)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_findings",
                to="core.site",
            ),
        ),
        migrations.AlterField(
            model_name="audit",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_review", "In Review"),
                    ("submitted_to_cb", "Submitted to CB"),
                    ("returned_for_correction", "Returned for Correction"),
                    ("technical_review", "Technical Review"),
                    ("decision_pending", "Decision Pending"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="evidencefile",
            index=models.Index(
                fields=["purge_after"], name="audits_evid_purge_a_b1f53c_idx"
            ),
        ),
        migrations.AddField(
            model_name="auditstatuslog",
            name="audit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_logs",
                to="audits.audit",
            ),
        ),
        migrations.AddField(
            model_name="auditstatuslog",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_status_changes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificationdecision",
            name="audit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certification_decision",
                to="audits.audit",
            ),
        ),
        migrations.AddField(
            model_name="certificationdecision",
            name="certifications_affected",
            field=models.ManyToManyField(
                help_text="Certifications affected by this decision",
                related_name="certification_decisions",
                to="core.certification",
            ),
        ),
        migrations.AddField(
            model_name="certificationdecision",
            name="decision_maker",
            field=models.ForeignKey(
                help_text="Person making final certification decision",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certification_decisions_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="technicalreview",
            name="audit",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="technical_review",
                to="audits.audit",
            ),
        ),
        migrations.AddField(
            model_name="technicalreview",
            name="reviewer",
            field=models.ForeignKey(
                help_text="CB staff member conducting technical review",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="technical_reviews_conducted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditstatuslog",
            index=models.Index(
                fields=["audit", "-changed_at"], name="audits_audi_audit_i_57d946_idx"
            ),
        ),
    ]
