# Generated by Django 5.2.8 on 2025-11-21 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audits", "0004_rootcausecategory_and_more"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["status"], name="audits_audi_status_2432b1_idx"),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["organization", "status"], name="audits_audi_organiz_eccc28_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["lead_auditor"], name="audits_audi_lead_au_563392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["verification_status"], name="audits_nonc_verific_f7dc33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["audit", "verification_status"],
                name="audits_nonc_audit_i_e1374b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="nonconformity",
            index=models.Index(
                fields=["category", "verification_status"],
                name="audits_nonc_categor_21a925_idx",
            ),
        ),
    ]
